---
- hosts: all
  sudo: true
  tasks:
  - yum: name={{item}} state=present
    with_items:
      - compat-libstdc++-33.x86_64
      - elfutils-libelf-devel
      - gcc-c++
      - libaio-devel
      - unixODBC
      - unixODBC-devel
  - group: name={{item}} state=present
    with_items:
      - dba
      - oinstall
  - user: name=oracle group=oinstall groups=dba state=present
  - sysctl: name="{{item.name}}" value="{{item.value}}" state=present ignoreerrors=yes
    with_items:
    - {name: "fs.file-max", value: "6815744"}
    - {name: "fs.aio-max-nr", value: "1048576"}
    - {name: "kernel.sem", value: "250 32000 100 128"}
    - {name: "kernel.shmall", value: "2097152"}
    - {name: "kernel.shmmax", value: "536870912"}
    - {name: "kernel.shmmni", value: "4096"}
    - {name: "net.ipv4.ip_local_port_range", value: "9000 65500"}
    - {name: "net.core.rmem_default", value: "262144"}
    - {name: "net.core.rmem_max", value: "4194304"}
    - {name: "net.core.wmem_default", value: "262144"}
    - {name: "net.core.wmem_max", value: "1048576"}
  - lineinfile: dest=/etc/security/limits.conf line="{{item}}"
    with_items:
      - "oracle soft nproc 2047"
      - "oracle hard nproc 16384"
      - "oracle soft nofile 1024"
      - "oracle hard nofile 65536"